plugins { id 'dev.architectury.loom-no-remap' }
dependencies {
    minecraft libs.minecraft
    compileOnly libs.fabric.loader
    compileOnly libs.mixin
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}
tasks.named('jar', Jar) { archiveFileName = "seamless-dogs-${project.version}-common.jar" }
tasks.named('sourcesJar', Jar) { archiveFileName = "seamless-dogs-${project.version}-common-sources.jar" }
