plugins { id 'dev.architectury.loom' }
dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()
    def apiJar = files(new File(rootProject.seamlessApiDirectory, "common/build/libs/seamless-api-${libs.versions.seamless.api.get()}-common.jar"))
    apiJar.builtBy gradle.includedBuild('seamless-api').task(':common:jar')
    api apiJar
    compileOnly libs.fabric.loader
    compileOnly libs.mixin
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}
tasks.named('jar', Jar) { archiveFileName = "seamless-dogs-${project.version}-common.jar" }
tasks.named('sourcesJar', Jar) { archiveFileName = "seamless-dogs-${project.version}-common-sources.jar" }
